model_name_or_path: /workspace/qwen2.5-7b-instruct
trust_remote_code: true

# === Finetuning (LoRA) ===
finetuning_type: lora
lora_target: q_proj,v_proj,k_proj,o_proj,gate_proj,up_proj,down_proj
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05

# === Dados ===
dataset: sharegpt_dialogs_style+sharegpt_dialogs_style_with_personality
dataset_dir: /workspace/whatsapp-autoresponder/data
template: qwen2            # prompt template compatível com Qwen2.*
cutoff_len: 4096
max_samples: -1            # usa tudo
overwrite_cache: true
preprocessing_num_workers: 2

# === Treino ===
output_dir: /workspace/output/qwen2.5-7b-instruct-lora
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-5
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.03
weight_decay: 0.0
logging_steps: 20
save_steps: 500
save_total_limit: 3
bf16: true                 # 3090 não tem bf16 nativo; se der erro, troque para fp16: true
tf32: true
gradient_checkpointing: true

# === Outros ===
report_to: none
ddp_timeout: 180000
