# Configurações do modelo
model_name_or_path: /workspace/qwen2.5-7b-instruct
output_dir: /workspace/whatsapp-autoresponder/output
logging_dir: /workspace/whatsapp-autoresponder/logs

# Configurações de dados
dataset_dir: /workspace/whatsapp-autoresponder/data
dataset: dialogs_style,dialogs_style_with_personality
template: qwen
cutoff_len: 1024
train_on_prompt: false
packing: true

# Configurações de treinamento
num_train_epochs: 3
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 2e-5
save_strategy: steps
save_steps: 500
eval_strategy: steps  # Substituído de evaluation_strategy
eval_steps: 500
logging_steps: 50
warmup_ratio: 0.03
lr_scheduler_type: cosine
fp16: true

# Configurações de LoRA
finetuning_type: lora
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target: all